#
# Copyright 2024 Tabs Data Inc.
#

name: tabsdata
controllers:
  init:
    concurrency: 1
    workers:
      - name: bootloader
        kind: processor
        location: relative
        program: bootloader
        inherit:
          - instance
          - repository
          - workspace
          - profile
  regular:
    concurrency: 0
    workers:
      - name: apiserver
        kind: processor
        location: relative
        program: apiserver
        parameters:
          - database-url: file://${TD_REPOSITORY}/database/tabsdata.db
          - storage-url: file://${TD_REPOSITORY}/storage
  ephemeral:
    concurrency: 8
    workers:
      - name: function
        kind: processor
        location: system
        program: tdmain
        concurrency: 8
        retries: 2
        arguments:
          - locks-folder
          - logs-folder
          - bin-folder
          - request-folder
          - response-folder
          - input-folder
          - output-folder
          - current-instance