#
# Copyright 2024 Tabs Data Inc.
#

name: tabsdata
controllers:
  init:
    concurrency: 1
    workers:
      - name: bootloader
        kind: processor
        location: relative
        program: bootloader
        inherit:
          - instance
          - repository
          - workspace
          - profile
      - name: apiserver-configuration-resolver
        kind: processor
        location: system
        program: _tdcfgrsv
        parameters:
          - input: ${TD_PATH_CONFIG}/proc/regular/apiserver/config/config.yaml
          - strategies: env,hashicorp
          - hashicorp-url: ""
          - hashicorp-token: ""
          - hashicorp-namespace: ""
          - env-hashicorp-url: ""
          - env-hashicorp-token: ""
          - env-hashicorp-namespace: ""
        set-state:
          state-type: blob
          state-key: apiserver-configuration
      - name: apiserver-mounts-options-extractor
        kind: processor
        location: system
        program: _tdmntext
        get-states:
          - state-type: blob
            state-key: apiserver-configuration
        set-state:
          state-type: map
          state-key: apiserver-mounts-options
  regular:
    concurrency: 0
    workers:
      - name: apiserver
        kind: processor
        location: relative
        program: apiserver
        parameters:
          - stdin-config: true
          - database-url: file://${TD_URI_REPOSITORY}/database/tabsdata.db
          - storage-url: file://${TD_URI_REPOSITORY}/storage
        get-states:
          - state-type: blob
            state-key: apiserver-configuration
  ephemeral:
    concurrency: 8
    workers:
      - name: function
        kind: processor
        location: system
        program: _tdinvoker
        concurrency: 8
        retries: 2
        arguments:
          - work
          - locks-folder
          - logs-folder
          - bin-folder
          - request-folder
          - response-folder
          - input-folder
          - output-folder
          - current-instance
        get-states:
          - state-type: map
            state-key: apiserver-mounts-options