#
# Copyright 2024 Tabs Data Inc.
#

name: tabsdata
controllers:
  init:
    concurrency: 1
    workers:
      - name: bootloader
        kind: processor
        location: relative
        program: bootloader
        inherit:
          - instance
          - repository
          - workspace
          - profile
      - name: uvinfo
        kind: processor
        location: system
        program: tduvinfo
        parameters:
          - output: versions
          - file: ${TD_PATH_INSTANCE}/workspace/work/etc/server.yaml
          - allowed_python_versions: allowed-py.yaml
          - allowed_packages_versions: allowed-pkg.yaml
      - name: apiserver-configuration-resolver
        kind: processor
        location: system
        program: tdcfgrsv
        parameters:
          - input: ${TD_PATH_CONFIG}/proc/regular/apiserver/config/config.yaml
          - strategies: env,hashicorp
          - hashicorp-url: ""
          - hashicorp-token: ""
          - hashicorp-namespace: ""
          - env-hashicorp-url: ""
          - env-hashicorp-token: ""
          - env-hashicorp-namespace: ""
        set-state:
          state-type: blob
          state-key: apiserver-configuration
      - name: apiserver-mounts-options-extractor
        kind: processor
        location: system
        program: tdmntext
        get-states:
          - state-type: blob
            state-key: apiserver-configuration
        set-state:
          state-type: map
          state-key: apiserver-mounts-options
  regular:
    concurrency: 0
    workers:
      - name: apiserver
        kind: processor
        location: relative
        program: apiserver
        parameters:
          - stdin-config: true
          - database-url: file://${TD_URI_REPOSITORY}/database/tabsdata.db
        get-states:
          - state-type: blob
            state-key: apiserver-configuration
      - name: janitor
        kind: processor
        location: system
        program: janitor
        parameters:
          - instance: ${TD_PATH_INSTANCE}
          - frequency: 900 # 15 minutes (seconds)
          - retention: 10800000 # 3 hours (milliseconds)
          - limit: 32
        arguments:
          - logs-folder
  ephemeral:
    concurrency: 8
    workers:
      - name: function
        kind: processor
        location: system
        program: tdinvoker
        concurrency: 8
        retries: 2
        arguments:
          - work
          - locks-folder
          - logs-folder
          - bin-folder
          - request-folder
          - response-folder
          - input-folder
          - output-folder
          - current-instance
        get-states:
          - state-type: map
            state-key: apiserver-mounts-options