#
# Copyright 2024 Tabs Data Inc.
#

[package]
description = "Tabsdata Plugin API"
edition = { workspace = true }
name = "td-interceptor-api"
publish = false
rust-version = { workspace = true }
version = { workspace = true }
license = { workspace = true }
authors = { workspace = true }
build = "build.rs"

[[example]]
name = "td-interceptor-api"
path = "examples/interceptor-api.rs"

[lib]

[features]
enterprise = []
td-test = ["dummy", "mock-env", "test-utils"]
dummy = []
mock-env = []
test_logging = []
test_tower_metadata = []
test-utils = []

[package.metadata.cargo-machete]
ignored = ["openssl", "td-build", "td-common", "toml"]

# Build dependencies

[build-dependencies]

# Internal dependencies

td-build = { workspace = true }

# External dependencies

toml = { workspace = true }

[dependencies]

# Internal dependencies

## Libraries

td-common = { workspace = true }
td-execution = { workspace = true }

# External dependencies

[target.'cfg(target_os = "linux")'.dependencies]
openssl = { workspace = true, features = ["vendored"] }
