#
# Copyright 2025 Tabs Data Inc.
#

[package]
description = "Tabsdata Polars Module Supporting TableFrame Features"
name = "ty-tableframe"

authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[[bin]]
name = "pystubs"
path = "src/pystubs.rs"

[[bin]]
name = "polars"
path = "src/polars.rs"

[lib]
name = "ty_tableframe"
crate-type = ["cdylib", "rlib"]

[package.metadata.maturin]
name = "tableframe"

[features]

without-polars-alloc = []

td-test = ["dummy"]
dummy = []

extension-module = ["pyo3/extension-module"]

[package.metadata.cargo-machete]
ignored = ["openssl", "td-build", "td-common", "td-error", "ta-tableframe", "te-tableframe", "thiserror", "toml", "serde", "arrow", "polars-arrow", "polars-mem-engine", "polars-plan", "rayon"]

# Build dependencies

[build-dependencies]

# Internal dependencies

[dependencies]

# Internal dependencies

## Libraries

td-build = { workspace = true }
td-common = { workspace = true }
td-error = { workspace = true }
te-tableframe = { workspace = true }
ta-tableframe = { workspace = true }

## Macros

# External dependencies

arrow = { workspace = true }
chrono = { workspace = true }
data-encoding = { workspace = true }
polars = { workspace = true, features = ["default", "fmt", "dtype-date", "timezones"] }
polars-plan = { workspace = true, features = ["python"] }
polars-mem-engine = { workspace = true, features = ["python"] }
pyo3 = { workspace = true, features = ["abi3-py312", "anyhow", "macros", "multiple-pymethods", "num-bigint", "num-complex", "num-rational", "rust_decimal", "serde", "smallvec"] }
pyo3-polars = { workspace = true, features = ["derive"] }
pyo3-stub-gen = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true, features = ["derive"] }
uuid7 = { workspace = true }


[target.'cfg(target_os = "linux")'.dependencies]
openssl = { workspace = true, features = ["vendored"] }
