#
# Copyright 2025 Tabs Data Inc.
#

[tasks.book_dguide]
category = "99 - Books"
description = "Read book 'Tabsdata Developer Guide'"
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/libraries/log.ds

    cd "${BOOK_DEVELOPER_GUIDE_FOLDER}"
    exec --fail-on-error mdbook serve --open
    ''']