#
# Copyright 2025 Tabs Data Inc.
#

[tasks.build_py]
category = "03 - Build"
description = "Task 'build' for Python projects"
run_task = [
    { name = [
        "build_py_ta_features",
        "build_py_ta_tableframe",
        "build_py_te_examples",
        "build_py_te_tableframe",
        "build_py_tabsdata",
        "build_py_connectors",
    ] }
]

[tasks.build_py_ta_features]
category = "03 - Build"
private = true

[tasks.build_py_ta_tableframe]
category = "03 - Build"
private = true

[tasks.build_py_te_examples]
category = "03 - Build"
private = true
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/libraries/log.ds

    cd "${PROJECT_PY_TE_EXAMPLES_FOLDER}/tabsdata/extensions/_examples/guides"

    debug "🚀 mdbook build"
    exec --fail-on-error mdbook build
    ''']

[tasks.build_py_te_tableframe]
category = "03 - Build"
private = true

[tasks.build_py_tabsdata]
category = "03 - Build"
private = true

[tasks.build_py_connectors]
category = "03 - Build"
private = true
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/libraries/log.ds

    connectors = glob_array ${CONNECTORS_PY_ROOT_FOLDER}/tabsdata_*

    for connector in ${connectors}
        is_connector = is_dir ${connector}
        if ${is_connector}
        end
    end
    ''']
