#
# Copyright 2025 Tabs Data Inc.
#

[tasks.build_py]
description = "Task 'build' for Python projects"
run_task = [
    { name = [
        "build_py_tabsdata",
        "build_py_td_features",
        "build_py_ta_tableframe",
        "build_py_te_tableframe",
        "build_py_td-sdk"
    ] }
]

[tasks.build_py_tabsdata]
private = true

[tasks.build_py_td_features]
private = true

[tasks.build_py_ta_tableframe]
private = true

[tasks.build_py_te_tableframe]
private = true

[tasks.build_py_td-sdk]
private = true