#
# Copyright 2025 Tabs Data Inc.
#

[tasks.clean_py]
description = "Task 'clean' for Python projects"
run_task = [
    { name = [
        "clean_py_root",
        "clean_py_td_features",
        "clean_py_ta_tableframe",
        "clean_py_te_tableframe",
        "clean_py_tabsdata",
        "clean_py_tabsdata_salesforce",
    ] }
]

[tasks.clean_py_root]
private = true
command = "python3"
args = ["${CLEAN_PYTHON_PY}", "${PROJECT_ROOT_FOLDER}", "py"]

[tasks.clean_py_td_features]
private = true
command = "python3"
args = ["${CLEAN_PYTHON_PY}", "${PROJECT_TD_FEATURES_FOLDER}", "py"]

[tasks.clean_py_ta_tableframe]
private = true
command = "python3"
args = ["${CLEAN_PYTHON_PY}", "${PROJECT_TA_TABLEFRAME_FOLDER}", "py"]

[tasks.clean_py_te_tableframe]
private = true
command = "python3"
args = ["${CLEAN_PYTHON_PY}", "${PROJECT_TD_TABLEFRAME_FOLDER}", "py"]

[tasks.clean_py_tabsdata]
private = true
command = "python3"
args = ["${CLEAN_PYTHON_PY}", "${PROJECT_TD_SDK_FOLDER}", "py"]

[tasks.clean_py_tabsdata_salesforce]
private = true
command = "python3"
args = ["${CLEAN_PYTHON_PY}", "${PROJECT_TABSDATA_SALESFORCE_FOLDER}", "py"]