#
# Copyright 2025 Tabs Data Inc.
#

[tasks.clean_py]
category = "01 - Clean"
description = "Task 'clean' for Python projects"
run_task = [
    { name = [
        "clean_py_ta_features",
        "clean_py_ta_tableframe",
        "clean_py_te_examples",
        "clean_py_te_tableframe",
        "clean_py_ty_tableframe",
        "clean_py_tabsdata",
        "clean_py_connectors",
        "clean_py_all",
    ] }
]

[tasks.clean_py_all]
category = "01 - Clean"
private = true
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/libraries/log.ds

    debug "🚀 python ${CLEAN_PY} ${PROJECT_TABSDATA_ROOT_FOLDER} py"
    exec --fail-on-error python ${CLEAN_PY} ${PROJECT_TABSDATA_ROOT_FOLDER} py
    ''']


[tasks.clean_py_ta_features]
category = "01 - Clean"
private = true
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/libraries/log.ds

    debug "🚀 python ${CLEAN_PY} ${PROJECT_PY_TA_FEATURES_FOLDER} py"
    exec --fail-on-error python ${CLEAN_PY} ${PROJECT_PY_TA_FEATURES_FOLDER} py
    ''']

[tasks.clean_py_ta_tableframe]
category = "01 - Clean"
private = true
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/libraries/log.ds

    debug "🚀 python ${CLEAN_PY} ${PROJECT_PY_TA_TABLEFRAME_FOLDER} py"
    exec --fail-on-error python ${CLEAN_PY} ${PROJECT_PY_TA_TABLEFRAME_FOLDER} py
    ''']


[tasks.clean_py_te_examples]
category = "01 - Clean"
private = true
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/libraries/log.ds

    debug "🚀 python ${CLEAN_PY} ${PROJECT_PY_TE_EXAMPLES_FOLDER} py"
    exec --fail-on-error python ${CLEAN_PY} ${PROJECT_PY_TE_EXAMPLES_FOLDER} py
    ''']

[tasks.clean_py_te_tableframe]
category = "01 - Clean"
private = true
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/libraries/log.ds

    debug "🚀 python ${CLEAN_PY} ${PROJECT_PY_TE_TABLEFRAME_FOLDER} py"
    exec --fail-on-error python ${CLEAN_PY} ${PROJECT_PY_TE_TABLEFRAME_FOLDER} py
    ''']

[tasks.clean_py_ty_tableframe]
category = "01 - Clean"
private = true
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/libraries/log.ds

    debug "🚀 python ${CLEAN_PY} ${PROJECT_PY_TY_TABLEFRAME_FOLDER} py"
    exec --fail-on-error python ${CLEAN_PY} ${PROJECT_PY_TY_TABLEFRAME_FOLDER} py
    ''']

[tasks.clean_py_tabsdata]
category = "01 - Clean"
private = true
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/libraries/log.ds

    debug "🚀 python ${CLEAN_PY} ${PROJECT_PY_TD_SDK_FOLDER} py"
    exec --fail-on-error python ${CLEAN_PY} ${PROJECT_PY_TD_SDK_FOLDER} py
    ''']

[tasks.clean_py_connectors]
category = "01 - Clean"
private = true
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/libraries/log.ds

    connectors = glob_array ${CONNECTORS_PY_ROOT_FOLDER}/tabsdata_*

    for connector in ${connectors}
        is_connector = is_dir ${connector}
        if ${is_connector}
            debug "🚀 python ${CLEAN_PY} ${connector} py"
            exec --fail-on-error python ${CLEAN_PY} ${connector} py
        end
    end
    ''']