#
# Copyright 2025 Tabs Data Inc.
#

[tasks.license_py]
category = "06 - Compliance"
description = "Task 'license' for Python projects"
run_task = [
    { name = [
        "license_check_py",
        "license_report_py"
    ] }
]

[tasks.license_check_py]
category = "06 - Compliance"
private = true
cwd = "${PROJECT_TABSDATA_ROOT_FOLDER}"
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/libraries/log.ds

    exec --fail-on-error pip-compile --no-strip-extras --quiet ./requirements/requirements-third-party-all.txt --output-file ./target/requirements.txt

    cd target

    license_cfg = readfile ../.cargo/licensecheck.cfg
    license_cfg_items = split ${license_cfg} \n

    authorized_licenses = set "--only-licenses"
    authorized_packages = set "--ignore-packages"

    current_section = set ""

    for item in ${license_cfg_items}
        item_trimmed = trim ${item}
        if not is_empty ${item_trimmed}
            starts_with_hash = starts_with ${item_trimmed} "#"
            if not ${starts_with_hash}
                starts_with_bracket = starts_with ${item_trimmed} "["
                if ${starts_with_bracket}
                    current_section = set ${item_trimmed}
                else
                    if equals ${current_section} "[authorized licenses]"
                        authorized_licenses = set "${authorized_licenses} \"${item_trimmed}\""
                    end
                    if equals ${current_section} "[authorized packages]"
                        authorized_packages = set "${authorized_packages} \"${item_trimmed}\""
                    end
                end
            end
        end
    end

    debug "🚀 licensecheck -r requirements.txt %{authorized_licenses} %{authorized_packages} --show-only-failing --zero"
    exec --fail-on-error licensecheck --license "PROPRIETARY" --requirements-paths requirements.txt %{authorized_licenses} %{authorized_packages} --show-only-failing --zero

    cd ..
    ''']

[tasks.license_report_py]
category = "06 - Compliance"
private = true
cwd = "${PROJECT_TABSDATA_ROOT_FOLDER}"
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/libraries/log.ds

    cd target

    exec --fail-on-error python ../devutils/automation/tasks/makers/td-scripts/report_licenses_py.py
    ''']