#
# Copyright 2025 Tabs Data Inc.
#

[tasks.license_rs]
category = "06 - Compliance"
description = "Task 'license' for Rust projects"
run_task = [
    { name = [
        "license_check_rs",
        "license_report_rs"
    ] }
]

[tasks.license_check_rs]
category = "06 - Compliance"
private = true
run_task = [
    { name = [
        "license_check_rs_macros",
        "license_check_rs_modules",
        "license_check_rs_expansions"
    ] }
]

[tasks.license_check_rs_macros]
category = "06 - Compliance"
private = true
run_task = [
    { name = [
        # "license_check_list_rs_macros",
        "license_check_deny_rs_macros"
    ] }
]

[tasks.license_check_rs_modules]
category = "06 - Compliance"
private = true
run_task = [
    { name = [
        # "license_check_list_rs_modules",
        "license_check_deny_rs_modules"
    ] }
]

[tasks.license_check_rs_expansions]
category = "06 - Compliance"
private = true
run_task = [
    { name = [
        # "license_check_list_rs_expansions",
        "license_check_deny_rs_expansions"
    ] }
]

[tasks.license_check_list_rs_macros]
category = "06 - Compliance"
private = true
command = "cargo"
args = ["license", "--manifest-path", "${PROJECT_RS_TD_MACROS_CARGO_TOML}", "--all-features"]

[tasks.license_check_deny_rs_macros]
private = true
cwd = "${PROJECT_TABSDATA_ROOT_FOLDER}"
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/libraries/log.ds

    exec --fail-on-error cargo %{td-toolchain-token}%{td-toolchain} deny --locked %{td-target-token} %{td-target} --log-level error --workspace --all-features --manifest-path ${PROJECT_RS_TD_MACROS_CARGO_TOML} check --config ${DENY_TOML} --hide-inclusion-graph license
    ''']

[tasks.license_check_list_rs_modules]
category = "06 - Compliance"
private = true
command = "cargo"
args = ["license", "--manifest-path", "${PROJECT_RS_TABSDATA_CARGO_TOML}", "--all-features"]

[tasks.license_check_deny_rs_modules]
category = "06 - Compliance"
private = true
cwd = "${PROJECT_TABSDATA_ROOT_FOLDER}"
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/libraries/log.ds

    exec --fail-on-error cargo %{td-toolchain-token}%{td-toolchain} deny --locked %{td-target-token} %{td-target} --log-level error --workspace --all-features --manifest-path ${PROJECT_RS_TABSDATA_CARGO_TOML} check --config ${DENY_TOML} --hide-inclusion-graph license
    ''']

[tasks.license_check_list_rs_expansions]
category = "06 - Compliance"
private = true
command = "cargo"
args = ["license", "--manifest-path", "${PROJECT_RS_TY_EXPANSIONS_CARGO_TOML}", "--all-features"]

[tasks.license_check_deny_rs_expansions]
private = true
cwd = "${PROJECT_TABSDATA_ROOT_FOLDER}"
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/libraries/log.ds

    exec --fail-on-error cargo %{td-toolchain-token}%{td-toolchain} deny --locked %{td-target-token} %{td-target} --log-level error --workspace --all-features --manifest-path ${PROJECT_RS_TY_EXPANSIONS_CARGO_TOML} check --config ${DENY_TOML} --hide-inclusion-graph license
    ''']

[tasks.license_report_rs]
category = "06 - Compliance"
private = true
cwd = "${PROJECT_TABSDATA_ROOT_FOLDER}"
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/libraries/log.ds

    exec --fail-on-error python ./devutils/automation/tasks/makers/td-scripts/report_licenses_rs.py
    ''']
