#
# Copyright 2025 Tabs Data Inc.
#

[tasks.lock_rs]
category = "02 - Tidy"
description = "Task 'lock' for Rust projects"
run_task = [
    { name = [
        "lock_rs_macros",
        "lock_rs_modules",
        "lock_rs_expansions",
    ] }
]

[tasks.lock_rs_macros]
category = "02 - Tidy"
private = true
cwd = "${PROJECT_TABSDATA_ROOT_FOLDER}"
command = "cargo"
args = ["generate-lockfile"]

[tasks.lock_rs_modules]
category = "02 - Tidy"
private = true
cwd = "${PROJECT_RS_TD_MACROS_FOLDER}"
command = "cargo"
args = ["generate-lockfile"]

[tasks.lock_rs_expansions]
category = "02 - Tidy"
private = true
cwd = "${PROJECT_RS_TY_EXPANSIONS_FOLDER}"
command = "cargo"
args = ["generate-lockfile"]
