#
# Copyright 2025 Tabs Data Inc.
#

[tasks.lock_rs]
category = "02 - Tidy"
description = "Task 'lock' for Rust projects"
run_task = [
    { name = [
        "lock_rs_macros",
        "lock_rs_modules",
        "lock_rs_expansions",
    ] }
]

[tasks.lock_rs_macros]
category = "02 - Tidy"
private = true
cwd = "${PROJECT_TABSDATA_ROOT_FOLDER}"
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/libraries/log.ds

    cd "${PROJECT_TABSDATA_ROOT_FOLDER}"
    debug "🚀 cargo generate-lockfile"
    exec --fail-on-error cargo generate-lockfile

    debug "🚀 cargo update --verbose -p planus --precise 1.1.1"
    exit_code = exec --get-exit-code cargo update --verbose -p planus --precise 1.1.1
    ''']


[tasks.lock_rs_modules]
category = "02 - Tidy"
private = true
cwd = "${PROJECT_TABSDATA_ROOT_FOLDER}"
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/libraries/log.ds

    cd "${PROJECT_RS_TD_MACROS_FOLDER}"

    debug "🚀 cargo generate-lockfile"
    exec --fail-on-error cargo generate-lockfile

    debug "🚀 cargo update --verbose -p planus --precise 1.1.1"
    exit_code = exec --get-exit-code cargo update --verbose -p planus --precise 1.1.1
    ''']

[tasks.lock_rs_expansions]
category = "02 - Tidy"
private = true
cwd = "${PROJECT_TABSDATA_ROOT_FOLDER}"
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/libraries/log.ds

    cd "${PROJECT_RS_TY_EXPANSIONS_FOLDER}"

    debug "🚀 cargo generate-lockfile"
    exec --fail-on-error cargo generate-lockfile

    debug "🚀 cargo update --verbose -p planus --precise 1.1.1"
    exit_code = exec --get-exit-code cargo update --verbose -p planus --precise 1.1.1
    ''']