#
# Copyright 2025 Tabs Data Inc.
#

[tasks.outdated_rs]
category = "04 - Check"
description = "Task 'outdated' for Rust projects"
run_task = [
    { name = [
        "outdated_rs_macros",
        "outdated_rs_modules",
        "outdated_rs_expansions"
    ] }
]


[tasks.outdated_rs_macros]
category = "04 - Check"
private = true
cwd = "${PROJECT_TABSDATA_ROOT_FOLDER}"
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/libraries/log.ds

    debug "🚀 ${td-cargo} upgrade --dry-run --compatible allow --incompatible allow --pinned allow --manifest-path ${PROJECT_RS_TD_MACROS_CARGO_TOML}"
    exec --fail-on-error ${td-cargo} upgrade --dry-run --compatible allow --incompatible allow --pinned allow --manifest-path ${PROJECT_RS_TD_MACROS_CARGO_TOML}
    ''']

[tasks.outdated_rs_modules]
category = "04 - Check"
private = true
cwd = "${PROJECT_TABSDATA_ROOT_FOLDER}"
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/libraries/log.ds

    debug "🚀 ${td-cargo} upgrade --dry-run --compatible allow --incompatible allow --pinned allow --manifest-path ${PROJECT_RS_TABSDATA_CARGO_TOML}"
    exec --fail-on-error ${td-cargo} upgrade --dry-run --compatible allow --incompatible allow --pinned allow --manifest-path ${PROJECT_RS_TABSDATA_CARGO_TOML}
    ''']

[tasks.outdated_rs_expansions]
category = "04 - Check"
private = true
cwd = "${PROJECT_TABSDATA_ROOT_FOLDER}"
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/libraries/log.ds

    debug "🚀 ${td-cargo} upgrade --dry-run --compatible allow --incompatible allow --pinned allow --manifest-path ${PROJECT_RS_TY_EXPANSIONS_CARGO_TOML}"
    exec --fail-on-error ${td-cargo} upgrade --dry-run --compatible allow --incompatible allow --pinned allow --manifest-path ${PROJECT_RS_TY_EXPANSIONS_CARGO_TOML}
    ''']