#
# Copyright 2025 Tabs Data Inc.
#

[tasks.permit_rs]
category = "00 - Verify"
description = "Task 'permit' for Rust projects"
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/libraries/log.ds

    tabsdata_rust_version = set 1.87.0
    set_env TABSDATA_RUST_VERSION ${tabsdata_rust_version}

    info "♻️️ Checking if the required Rust version is installed..."

    rustc = which rustc
    if equals ${rustc} ""
        error "🚫🚫🚫🚫🚫 Rust is not available. Make aborted."
        assert_fail
    end

    result = exec rustc --version
    code = set ${result.code}
    if not equals ${code} "0"
        error "🚫🚫🚫🚫🚫 Rust is available but unusable. Make aborted."
        assert_fail
    end

    version = trim ${result.stdout}
    info "❇️ Rust version: ${version}"

    result = exec python -c "import os, sys, subprocess; v = tuple(map(int, os.environ['TABSDATA_RUST_VERSION'].split('.'))); r = subprocess.check_output(['rustc', '--version']).decode().split()[1]; rv = tuple(map(int, r.split('.'))); sys.exit(0 if rv >= v else 1)"
    code = set ${result.code}
    if not equals ${code} "0"
        error "🚫🚫🚫🚫🚫 The Rust version is lesser than requited Rust version < ${tabsdata_rust_version} >. Make aborted."
        assert_fail
    end
    ''']