#
# Copyright 2025 Tabs Data Inc.
#

[package]
description = "Tabsdata Tower Features"
name = "td-tower"

authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lib]

[features]
enterprise = []
td-test = ["dummy", "mock-env", "test-utils"]
dummy = []
mock-env = []
test_logging = []
test_tower_metadata = []
test-utils = []

[package.metadata.cargo-machete]
ignored = ["openssl", "serde_json", "td-build", "thiserror", "utoipa", "strum", "toml"]

# Build dependencies

[build-dependencies]

# Internal dependencies

# External dependencies

[dependencies]

# Internal dependencies

## Macros

td-apiforge = { workspace = true }
tm-tower = { workspace = true }

## Libraries

td-database = { workspace = true }
td-error = { workspace = true }

# External dependencies

async-trait = { workspace = true }
axum = { workspace = true }
derive_builder = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
getset = { workspace = true }
http = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
strum = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tower = { workspace = true }
tower-layer = { workspace = true }
tower-service = { workspace = true }
tracing = { workspace = true }
utoipa = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
openssl = { workspace = true, features = ["vendored"] }
