//
// Copyright 2025 Tabs Data Inc.
//

#[td_type::dxo]
pub mod defs {
    use crate::types::bool::{DataChanged, HasData};
    use crate::types::i32::TableFunctionParamPos;
    use crate::types::i64::{ColumnCount, RowCount};
    use crate::types::id::{
        CollectionId, ExecutionId, FunctionRunId, FunctionVersionId, TableDataVersionId, TableId,
        TableVersionId, TransactionId, UserId,
    };
    use crate::types::string::{
        CollectionName, DataLocation, FunctionName, SchemaHash, StorageVersion, TableName, UserName,
    };
    use crate::types::timestamp::{AtTime, TriggeredOn};
    use crate::types::typed_enum::FunctionRunStatus;

    #[td_type::Dao]
    #[dao(sql_table = "table_data_versions")]
    pub struct TableDataVersionDB {
        #[builder(default)]
        #[td_type(extractor)]
        pub id: TableDataVersionId,
        pub collection_id: CollectionId,
        pub table_id: TableId,
        pub name: TableName,
        pub table_version_id: TableVersionId,
        #[td_type(extractor)]
        pub function_version_id: FunctionVersionId,
        #[builder(default)]
        pub has_data: Option<HasData>,
        #[builder(default)]
        pub column_count: Option<ColumnCount>,
        #[builder(default)]
        pub row_count: Option<RowCount>,
        #[builder(default)]
        pub schema_hash: Option<SchemaHash>,
        pub execution_id: ExecutionId,
        pub transaction_id: TransactionId,
        pub function_run_id: FunctionRunId,
        pub function_param_pos: TableFunctionParamPos,
    }

    #[td_type::Dao]
    #[dao(
        sql_table = "table_data_versions__with_function",
        versioned(order_by = "triggered_on", partition_by = "table_id"),
        states(
            Committed = &[&FunctionRunStatus::Committed],
        )
    )]
    #[inherits(TableDataVersionDB)]
    pub struct TableDataVersionDBWithFunction {
        pub triggered_on: TriggeredOn,
        pub triggered_by_id: UserId,
        pub started_on: Option<AtTime>,
        pub ended_on: Option<AtTime>,
        pub status: FunctionRunStatus,
        pub data_location: DataLocation,
        pub storage_version: StorageVersion,

        // Only available when this version has data, even if it is not generated by this version
        // (has_data or !has_data and previous version has_data)
        pub with_data_table_data_version_id: Option<TableDataVersionId>,
        pub with_data_column_count: Option<ColumnCount>,
        pub with_data_row_count: Option<RowCount>,
        pub with_data_schema_hash: Option<SchemaHash>,
    }

    #[td_type::Dao]
    #[dao(
        sql_table = "table_data_versions__active",
        states(
            All = &[],
        )
    )]
    #[inherits(TableDataVersionDBWithFunction)]
    pub struct ActiveTableDataVersionDB {}

    #[td_type::Dto]
    #[td_type(builder(try_from = ActiveTableDataVersionDB))]
    #[derive(Eq, PartialEq, Hash)]
    pub struct ExecutionTableDataVersionRead {
        pub id: TableDataVersionId,
        pub collection_id: CollectionId,
        pub table_id: TableId,
        pub name: TableName,
        pub table_version_id: TableVersionId,
        pub function_version_id: FunctionVersionId,
        pub has_data: Option<HasData>,
        pub execution_id: ExecutionId,
        pub transaction_id: TransactionId,
        pub function_run_id: FunctionRunId,
        pub function_param_pos: Option<TableFunctionParamPos>,

        pub triggered_on: TriggeredOn,
        pub triggered_by_id: UserId,
        pub started_on: Option<AtTime>,
        pub ended_on: Option<AtTime>,
        pub status: FunctionRunStatus,
        pub with_data_table_data_version_id: Option<TableDataVersionId>,
    }

    #[td_type::Dao]
    #[dao(sql_table = "table_data_versions__with_names")]
    #[inherits(TableDataVersionDBWithFunction)]
    pub struct TableDataVersionDBWithNames {
        pub collection: CollectionName,
        pub function: FunctionName,
        pub created_by: UserName,
    }

    #[td_type::Dto]
    #[dto(list(on = TableDataVersionDBWithNames))]
    #[td_type(builder(try_from = TableDataVersionDBWithNames))]
    pub struct TableDataVersion {
        #[dto(list(pagination_by = "+", filter, filter_like))]
        pub id: TableDataVersionId,
        #[dto(list(filter, filter_like, order_by))]
        pub collection_id: CollectionId,
        #[dto(list(filter, filter_like, order_by))]
        pub table_id: TableId,
        #[dto(list(filter, filter_like, order_by))]
        pub name: TableName,
        #[dto(list(filter, filter_like, order_by))]
        pub table_version_id: TableVersionId,
        #[dto(list(filter, filter_like, order_by))]
        pub function_version_id: FunctionVersionId,
        #[td_type(builder(field = "with_data_column_count"))]
        pub column_count: Option<ColumnCount>,
        #[td_type(builder(field = "with_data_row_count"))]
        pub row_count: Option<RowCount>,
        #[dto(list(filter))]
        #[td_type(builder(field = "with_data_schema_hash"))]
        pub schema_hash: Option<SchemaHash>,
        #[td_type(builder(field = "has_data"))]
        #[dto(list(filter, filter_like, order_by))]
        pub data_changed: DataChanged,
        #[dto(list(filter, filter_like, order_by))]
        pub execution_id: ExecutionId,
        #[dto(list(filter, filter_like, order_by))]
        pub transaction_id: TransactionId,
        #[dto(list(filter, filter_like, order_by))]
        pub function_run_id: FunctionRunId,
        #[dto(list(filter, filter_like, order_by))]
        pub function_param_pos: Option<TableFunctionParamPos>,

        #[td_type(builder(field = "triggered_on"))]
        #[dto(list(filter, filter_like, order_by))]
        pub created_at: TriggeredOn,
        #[dto(list(filter, filter_like, order_by))]
        pub triggered_by_id: UserId,
        #[dto(list(filter, filter_like, order_by))]
        pub started_on: Option<AtTime>,
        #[dto(list(filter, filter_like, order_by))]
        pub ended_on: Option<AtTime>,
        #[dto(list(filter, filter_like, order_by))]
        pub status: FunctionRunStatus,

        #[dto(list(filter, filter_like, order_by))]
        pub collection: CollectionName,
        #[dto(list(filter, filter_like, order_by))]
        pub function: FunctionName,
        #[dto(list(filter, filter_like, order_by))]
        pub created_by: UserName,
    }

    #[td_type::Dao]
    #[dao(sql_table = "table_data_versions")]
    pub struct UpdateTableDataVersionDB {
        #[dao(immutable)]
        #[builder(default)]
        pub has_data: Option<HasData>,
        #[dao(immutable)]
        #[builder(default)]
        pub column_count: Option<ColumnCount>,
        #[dao(immutable)]
        #[builder(default)]
        pub row_count: Option<RowCount>,
        #[dao(immutable)]
        #[builder(default)]
        pub schema_hash: Option<SchemaHash>,
    }
}
