#
# Copyright 2025 Tabs Data Inc.
#

[package]
description = "Tabsdata API Services"
edition = { workspace = true }
name = "td-services"
publish = false
rust-version = { workspace = true }
version = { workspace = true }
license = { workspace = true }
authors = { workspace = true }

[lib]

[features]
enterprise = []
td-test = ["dummy", "mock-env", "test-utils"]
dummy = []
mock-env = []
sqlx_log = []
test_logging = []
test_tower_metadata = ["td-tower/test_tower_metadata"]
test-utils = []

[package.metadata.cargo-machete]
ignored = ["openssl", "strum_macros", "thiserror", "tower"]

# Build dependencies

[build-dependencies]

# Internal dependencies

# External dependencies

[dependencies]

# Internal dependencies

## Macros


## Libraries

ta-execution = { workspace = true }
td-authz = { workspace = true }
td-common = { workspace = true }
td-database = { workspace = true }
td-error = { workspace = true }
td-execution = { workspace = true }
td-objects = { workspace = true }
td-security = { workspace = true }
td-tower = { workspace = true }

## Extensions

te-execution = { workspace = true }

# External dependencies

argon2 = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true, features = ["macros"] }
chrono = { workspace = true }
getset = { workspace = true }
jsonwebtoken = { workspace = true }
lazy_static = { workspace = true }
serde = { workspace = true}
sqlx = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
tracing = { workspace = true }


[dev-dependencies]
td-objects = { workspace = true, features = ["td-test"] }
td-test = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
openssl = { workspace = true, features = ["vendored"] }
