#
# Copyright 2025 Tabs Data Inc.
#

[package]
description = "Tabsdata API Services"
edition = { workspace = true }
name = "td-services"
publish = false
rust-version = { workspace = true }
version = { workspace = true }
license = { workspace = true }
authors = { workspace = true }

[lib]

[features]
enterprise = []
td-test = ["dummy", "mock-env", "test-utils"]
dummy = []
mock-env = []
sqlx_log = []
test_logging = []
test_tower_metadata = ["td-tower/test_tower_metadata"]
test-utils = []

[package.metadata.cargo-machete]
ignored = ["openssl", "tower"]

# Build dependencies

[build-dependencies]

# Internal dependencies

# External dependencies

[dependencies]

# Internal dependencies

## Macros

td-error = { workspace = true }

## Libraries

td-common = { workspace = true }
td-database = { workspace = true }
td-objects = { workspace = true }
td-security = { workspace = true }
td-tower = { workspace = true }

# External dependencies

sqlx = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }

[dev-dependencies]
td-objects = { workspace = true, features = ["td-test"] }

[target.'cfg(target_os = "linux")'.dependencies]
openssl = { workspace = true, features = ["vendored"] }
