#
# Copyright 2025 Tabs Data Inc.
#

[package]
description = "Tabsdata API Services"
name = "td-services"

authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lib]

[features]
enterprise = []
td-test = ["dummy", "mock-env", "test-utils"]
dummy = []
mock-env = []
sqlx_log = []
test_logging = []
test_tower_metadata = ["td-tower/test_tower_metadata"]
test-utils = []

[package.metadata.cargo-machete]
ignored = ["openssl", "strum_macros", "thiserror", "tower"]

# Build dependencies

[build-dependencies]

# Internal dependencies

# External dependencies

[dependencies]

# Internal dependencies

## Macros


## Libraries

ta-execution = { workspace = true }
td-authz = { workspace = true }
td-common = { workspace = true }
td-database = { workspace = true }
td-error = { workspace = true }
td-execution = { workspace = true }
td-objects = { workspace = true }
td-security = { workspace = true }
td-storage = { workspace = true }
td-tower = { workspace = true }

## Extensions

te-execution = { workspace = true }

# External dependencies

argon2 = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
getset = { workspace = true }
hex = { workspace = true }
http = { workspace = true }
itertools = { workspace = true }
jsonwebtoken = { workspace = true }
lazy_static = { workspace = true }
polars = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
sqlx = { workspace = true }
strum_macros = { workspace = true }
testdir = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tower = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
td-common = { workspace = true, features = ["td-test"] }
td-objects = { workspace = true, features = ["td-test"] }
td-test = { workspace = true, features = ["td-test"] }

[target.'cfg(target_os = "linux")'.dependencies]
openssl = { workspace = true, features = ["vendored"] }