# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins

def grok_fields(pattern:builtins.str) -> builtins.list[builtins.str]: ...

def grok_patterns() -> builtins.dict[builtins.str, builtins.str]: ...

