#
# Copyright 2025 Tabs Data Inc.
#

[package]
description = "Tabsdata REST API Types"
edition = { workspace = true }
name = "td-rest"
publish = false
rust-version = { workspace = true }
version = { workspace = true }
license = { workspace = true }
authors = { workspace = true }

[lib]

[features]
enterprise = []
td-test = ["dummy", "mock-env", "test-utils"]
dummy = []
mock-env = []
sqlx_log = []
test_logging = []
test-utils = []

[package.metadata.cargo-machete]
ignored = ["openssl"]

# Build dependencies

[build-dependencies]

# Internal dependencies

# External dependencies

[dependencies]

# Internal dependencies

## Macros

td-error = { workspace = true }

## Libraries

td-authz = { workspace = true }
td-common = { workspace = true }
td-objects = { workspace = true }
td-security = { workspace = true }

# External dependencies

async-trait = { workspace = true }

[dev-dependencies]
td-objects = { workspace = true, features = ["td-test"] }
td-test = { workspace = true }
derive_builder = { workspace = true }
getset = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_valid = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true }
utoipa = { workspace = true, features = ["axum_extras", "preserve_order", "uuid"] }

[target.'cfg(target_os = "linux")'.dependencies]
openssl = { workspace = true, features = ["vendored"] }