#
# Copyright 2025 Tabs Data Inc.
#

[package]
description = "Tabsdata In/Out Data Mover"
name = "td-shuttle"
build = "build.rs"

authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lib]

[features]
api-docs = []
enterprise = []
td-test = ["dummy", "mock-env", "test-utils"]
dummy = []
mock-env = []
sqlx_log = []
test_logging = []
test-utils = []

[package.metadata.cargo-machete]
ignored = ["openssl", "strum", "toml", "td-build", "tm-workspace"]

# Build dependencies

[build-dependencies]

# Internal dependencies

td-build = { workspace = true }

# External dependencies

toml = { workspace = true }

[dependencies]

# Internal dependencies


## Macros

td-build = { workspace = true }
tm-workspace = { workspace = true }

## Libraries

td-common = { workspace = true }
td-error = { workspace = true }
td-process = { workspace = true }

## Extensions

# External dependencies

async-trait = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true, features = ["derive"] }
clap_derive = { workspace = true }
derive_builder = { workspace = true }
futures-util = { workspace = true }
getset = { workspace = true }
itertools = { workspace = true }
object_store = { workspace = true, features = ["aws", "azure", "gcp", "http"] }
polars = { workspace = true, features = ["lazy", "polars-lazy", "async", "csv", "json", "parquet", "cloud", "aws", "azure", "gcp", "sql"] }
polars-io = { version = "0.50.0", features = ["cloud"]  }
polars-parquet-format = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
strum = { workspace = true, features = ["derive"] }
testdir = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
url = { workspace = true, features = ["serde"] }
wildmatch = { workspace = true }
uuid = {  workspace = true, features = ["v4"] }

[dev-dependencies]
td-common = { workspace = true, features = ["td-test"] }

[target.'cfg(target_os = "linux")'.dependencies]
openssl = { workspace = true, features = ["vendored"] }
