#
# Copyright 2025 Tabs Data Inc.
#

[tasks.teardown]
script_runner = "@duckscript"
script = [
    '''
    !include_files ./make/libraries/log.ds

    os_family = os_family
    if eq ${os_family} "windows"
        cm_run_task teardown_windows
    else
        if eq ${os_family} "mac"
            cm_run_task teardown_mac
        else
            if eq ${os_family} "linux"
                cm_run_task teardown_linux
            end
        end
    end
    ''']

[tasks.teardown_windows]
ignore_errors = true
condition = { env = { MAKE_SUCCESS = "true" } }

[tasks.teardown_linux]
ignore_errors = true
condition = { env = { MAKE_SUCCESS = "true" } }

[tasks.teardown_mac]
ignore_errors = true
condition = { env = { MAKE_SUCCESS = "true" } }
script = [
    '''
    if command -v viu &> /dev/null; then
        echo
        viu --width 32 ${ROOT_PROJECT_TABSDATA_FOLDER}/make/resources/images/ferri-happy.png
    fi
    if command -v lolcat &> /dev/null && command -v figlet &> /dev/null; then
        echo
        figlet -f ${ROOT_PROJECT_TABSDATA_FOLDER}/make/resources/fonts/3d.flf Done! | lolcat
        echo
    else
        echo "✅ Ok!. You can install figlet and lolcat for cooler messages..."
    fi
    ''']