#
# Copyright 2025 Tabs Data Inc.
#

[package]
description = "Tabsdata Python Enablement Components"
name = "td-python"

authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lib]

[features]
enterprise = []
td-test = ["dummy", "mock-env", "test-utils"]
dummy = []
mock-env = []
test_logging = []
test_tower_metadata = []
test-utils = []

[package.metadata.cargo-machete]
ignored = ["openssl", "strum_macros", "td-build", "thiserror", "toml"]

# Build dependencies

[build-dependencies]

# Internal dependencies

[dependencies]

# Internal dependencies

## Libraries

td-build = { workspace = true }
td-common = { workspace = true }
td-error = { workspace = true }

## Macros

# External dependencies

rand = { workspace = true }
semver = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
openssl = { workspace = true, features = ["vendored"] }
