#
# Copyright 2025 Tabs Data Inc.
#

[package]
description = "Tabsdata Process Tools"
name = "td-process"

authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lib]

[features]
enterprise = []
td-test = ["dummy", "mock-env", "test-utils"]
dummy = []
mock-env = []
test_logging = []
test_tower_metadata = []
test-utils = []

[package.metadata.cargo-machete]
ignored = ["openssl", "td-build", "thiserror", "strum", "toml"]

# Build dependencies

[build-dependencies]

# Internal dependencies

[dependencies]

# Internal dependencies

## Libraries

td-build = { workspace = true }
td-common = { workspace = true }
    td-objects = { workspace = true }

## Macros

# External dependencies

clap = { workspace = true, features = ["derive"] }
clap_derive = { workspace = true }
config = { workspace = true, features = ["yaml"] }
dir-size = { workspace = true }
getset = { workspace = true }
ignore = { workspace = true }
indexmap = { workspace = true }
num-format = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_yaml = { workspace = true }
strum = { workspace = true, features = ["derive"] }
sysinfo = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
openssl = { workspace = true, features = ["vendored"] }
