#
# Copyright 2024 Tabs Data Inc.
#

[package]
description = "Tabsdata Objects Structures"
name = "td-objects"

authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lib]

[features]
enterprise = []
td-test = ["dummy", "mock-env", "test-utils"]
dummy = []
mock-env = []
sqlx_log = []
test_logging = []
test_tower_metadata = []
test-utils = []

[package.metadata.cargo-machete]
ignored = ["openssl", "td-build", "td-objects", "td-schema", "thiserror", "toml"]

# Build dependencies

[build-dependencies]

# Internal dependencies

# External dependencies

[dependencies]

# Internal dependencies

## Macros

td-apiforge = { workspace = true }
td-type = { workspace = true }

## Libraries

td-common = { workspace = true }
td-database = { workspace = true }
td-error = { workspace = true }
td-security = { workspace = true }
td-storage = { workspace = true }
td-test = { workspace = true }
td-tower = { workspace = true }
td-transaction = { workspace = true }

# External dependencies

async-trait = { workspace = true }
axum = { workspace = true }
bytes = { workspace = true }
constcat = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
derive_builder = { workspace = true }
derive-new = { workspace = true }
futures-util = { workspace = true }
getset = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
paste = { workspace = true }
polars = { workspace = true }
regex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_valid = { workspace = true }
sqlx = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
utoipa = { workspace = true, features = ["axum_extras", "preserve_order", "uuid"] }
tracing = { workspace = true }

[dev-dependencies]
td-database = { workspace = true, features = ["td-test"] }
td-objects = { workspace = true, features = ["td-test"] }
td-schema = { workspace = true, features = ["td-test"] }

[target.'cfg(target_os = "linux")'.dependencies]
openssl = { workspace = true, features = ["vendored"] }
