#
# Copyright 2024 Tabs Data Inc.
#

[package]
description = "Tabsdata Xtask Library"
edition = { workspace = true }
name = "td-xtask"
publish = false
rust-version = { workspace = true }
version = { workspace = true }
license = { workspace = true }
authors = { workspace = true }

[features]

td-test = ["dummy", "mock-env", "test-utils"]
dummy = []
mock-env = []
test-utils = []

[dependencies]

# Internal dependencies

# External dependencies

clap = { workspace = true }
clap_derive = { workspace = true }