#
# Copyright 2025 Tabs Data Inc.
#

[package]
description = "Tabsdata Supervisor"
name = "td-supervisor"
build = "build.rs"

authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
readme = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
version = { workspace = true }

[lib]

[features]
api-docs = []
enterprise = []
td-test = ["dummy", "mock-env", "test-utils"]
dummy = []
mock-env = []
sqlx_log = []
test_logging = []
test-utils = []

[package.metadata.cargo-machete]
ignored = ["openssl", "ignore", "indicatif", "strum", "toml", "tm-workspace"]

# Build dependencies

[build-dependencies]

# Internal dependencies

td-build = { workspace = true }
td-python = { workspace = true }

# External dependencies

toml = { workspace = true }

[dependencies]

# Internal dependencies

## Macros

td-build = { workspace = true }
tm-workspace = { workspace = true }

## Libraries

td-apiserver = { workspace = true }
td-common = { workspace = true }
td-error = { workspace = true }
te-tableframe = { workspace = true }
ta-tableframe = { workspace = true }
td-process = { workspace = true }
td-python = { workspace = true }

## Extensions

# External dependencies

async-trait = { workspace = true }
atomic_enum = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true, features = ["derive"] }
clap_derive = { workspace = true }
derive_builder = { workspace = true }
dirs = { workspace = true }
futures = { workspace = true }
getset = { workspace = true }
http = { workspace = true }
humantime = { workspace = true }
indicatif = { workspace = true }
ignore = { workspace = true }
include_dir = { workspace = true }
indexmap = { workspace = true }
linemux = { workspace = true }
num-format = { workspace = true }
path-slash = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
strum = { workspace = true }
sysinfo = { workspace = true }
tabled = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
url = { workspace = true, features = ["serde"] }
walkdir = { workspace = true }

[dev-dependencies]
ta-tableframe = { workspace = true, features = ["td-test"] }
te-tableframe = { workspace = true, features = ["td-test"] }
td-common = { workspace = true, features = ["td-test"] }

[target.'cfg(target_os = "linux")'.dependencies]
openssl = { workspace = true, features = ["vendored"] }

