#
# Copyright 2024 Tabs Data Inc.
#

name: tabsdata
controllers:
  init:
    concurrency: 1
    workers:
      - name: bootloader
        kind: processor
        location: relative
        program: bootloader
        inherit:
          - instance
          - repository
          - workspace
          - profile
      - name: uvinfo
        kind: processor
        location: system
        program: _tduvinfo
        parameters:
          - output: versions
          - file: ${TD_PATH_INSTANCE}/workspace/work/etc/pyversions.dat
      - name: apiserver-configuration-resolver
        kind: processor
        location: system
        program: _tdcfgrsv
        parameters:
          - input: ${TD_PATH_CONFIG}/proc/regular/apiserver/config/config.yaml
          - strategies: env,hashicorp
          - hashicorp-url: ""
          - hashicorp-token: ""
          - hashicorp-namespace: ""
          - env-hashicorp-url: ""
          - env-hashicorp-token: ""
          - env-hashicorp-namespace: ""
        set-state:
          state-type: blob
          state-key: apiserver-configuration
      - name: apiserver-mounts-options-extractor
        kind: processor
        location: system
        program: _tdmntext
        get-states:
          - state-type: blob
            state-key: apiserver-configuration
        set-state:
          state-type: map
          state-key: apiserver-mounts-options
      - name: janitor
        kind: processor
        location: system
        program: janitor
        parameters:
          - instance: ${TD_PATH_INSTANCE}
          - frequency: 900 # 15 minutes (seconds)
          - retention: 10800000 # 3 hours (milliseconds)
          - limit: 32
        arguments:
          - logs-folder
  regular:
    concurrency: 0
    workers:
      - name: apiserver
        kind: processor
        location: relative
        program: apiserver
        parameters:
          - stdin-config: true
          - database-url: file://${TD_URI_REPOSITORY}/database/tabsdata.db
          - storage-url: file://${TD_URI_REPOSITORY}/storage
        get-states:
          - state-type: blob
            state-key: apiserver-configuration
      - name: p01
        kind: processor
        location: relative
        program: examples/hal
        inherit:
          - work
      - name: p02
        kind: processor
        location: relative
        program: examples/hal
        inherit:
          - work
      - name: p03
        kind: processor
        location: relative
        program: examples/hal
        inherit:
          - work
      - name: p04
        kind: processor
        location: relative
        program: examples/hal
        inherit:
          - work
      - name: p05
        kind: processor
        location: relative
        program: examples/hal
        inherit:
          - work
  ephemeral:
    concurrency: 8
    workers:
      - name: function
        kind: processor
        location: system
        program: tdinvoker
        concurrency: 8
        retries: 2
        arguments:
          - work
          - locks-folder
          - logs-folder
          - bin-folder
          - request-folder
          - response-folder
          - input-folder
          - output-folder
          - current-instance
        get-states:
          - state-type: map
            state-key: apiserver-mounts-options
      - name: tars
        location: relative
        program: examples/tars
        concurrency: 1