#
# Copyright 2024 Tabs Data Inc.
#

name: tabsdata
controllers:
  init:
    concurrency: 1
    workers:
      - name: bootloader
        kind: processor
        location: relative
        program: bootloader
        inherit:
          - instance
          - repository
          - workspace
          - profile
  regular:
    concurrency: 0
    workers:
      - name: apiserver
        kind: processor
        location: relative
        program: apiserver
        parameters:
          - database-url: file://${TD_URI_REPOSITORY}/database/tabsdata.db
          - storage-url: file://${TD_URI_REPOSITORY}/storage
      - name: p01
        kind: processor
        location: relative
        program: examples/hal
        inherit:
          - work
      - name: p02
        kind: processor
        location: relative
        program: examples/hal
        inherit:
          - work
      - name: p03
        kind: processor
        location: relative
        program: examples/hal
        inherit:
          - work
      - name: p04
        kind: processor
        location: relative
        program: examples/hal
        inherit:
          - work
      - name: p05
        kind: processor
        location: relative
        program: examples/hal
        inherit:
          - work
  ephemeral:
    concurrency: 8
    workers:
      - name: function
        kind: processor
        location: system
        program: _tdinvoker
        concurrency: 8
        retries: 2
        arguments:
          - locks-folder
          - logs-folder
          - bin-folder
          - request-folder
          - response-folder
          - input-folder
          - output-folder
          - current-instance
      - name: tars
        location: relative
        program: examples/tars
        concurrency: 1