#
# Copyright 2024 Tabs Data Inc.
#

name: Teardown
description: Tears down the environment for integration and release builds

inputs:
  working-directory:
    required: false
    default: .
  shell:
    required: false
    default: bash

defaults:
  run:
    shell: bash
    working-directory: .

runs:
  using: "composite"

  steps:

    - name: Remove tests virtual environments
      id: remove_test_venv
      if: always()
      shell: ${{ inputs.shell }}
      run: find ~/.pyenv/ -name 'python_environment_*' -exec rm -rf {} + || true
      working-directory: ${{ inputs.working-directory }}